---
all:
  children:
    master:
      hosts:
        master-node:
          ansible_host: 192.168.1.10
          ansible_user: ubuntu
    workers:
      hosts:
        worker1:
          ansible_host: 192.168.1.11
          ansible_user: ubuntu
        worker2:
          ansible_host: 192.168.1.12
          ansible_user: ubuntu
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
