- name: OS Basic Configuration
  hosts: all
  become: true
  tasks:
    - name: Disable ufw
      community.general.ufw:
        state: disabled

    - name: Disable current swap
      ansible.builtin.command: swapoff -a

    - name: Remove swap from fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '.*swap.*'
        state: absent

    - name: Load kernel modules for k8s
      ansible.builtin.copy:
        content: |
          br_netfilter
          overlay
        dest: /etc/modules-load.d/k8s.conf

    - name: Load br_netfilter module
      ansible.builtin.modprobe:
        name: br_netfilter
        state: present

    - name: Load overlay module
      ansible.builtin.modprobe:
        name: overlay
        state: present

    - name: Configure k8s sysctl parameters
      ansible.builtin.copy:
        content: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1
        dest: /etc/sysctl.d/k8s.conf

    - name: Apply sysctl changes
      ansible.builtin.command: sysctl --system
